services:
  db:
    image: mysql:8.0
    container_name: mysql_gerenciamento_pedidos
    restart: always
    environment:
      MYSQL_DATABASE: gerenciamento_pedidos
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - network_gerenciamento_pedidos

  app:
    image: glaudencio123/gerenciamento-de-pedidos:v4
    container_name: app_gerenciamento_de_pedidos
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DOTENV_PATH: /app
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - .env:/app/.env
    networks:
      - network_gerenciamento_pedidos

volumes:
  db_data:

networks:
  network_gerenciamento_pedidos: