spring:
  application:
    name: GerenciamentoDePedidos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_DB_URL}
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
logging:
  level:
    root: INFO
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics
  endpoint:
    health:
      show-details: always